### ISSUE TITLE
Bi directional?

### ISSUE THREAD

**Issue by starfishmod** [valentin12/serial-to-midi#1]
Is it possible to make this bi-directional? I know this is an old project but it is very useful to my needs :)
Thanks for making this!

**Comment by valentin12** [comment]
I think it should be possible. Writing to the port is just [that](http://www.cmrr.umn.edu/~strupp/serial.html#2_5_3). [This page](http://users.suse.com/~mana/alsa090_howto.html#sect04) describes how to read and write ALSA MIDI events. The most work will probably be the backward mapping from ALSA MIDI event to the binary representation needed for serial.
Do you want (and are you able) to help with the implementation?

**Comment by starfishmod** [comment]
I would love to help but my C coding is basic beyond measure - in other words I tried to hack something together based on you code earlier today and failed dismally :)

**Comment by valentin12** [comment]
I think it should work like this, can you do some testing? The changes are in the branch [bidirectional](https://github.com/valentin12/serial-to-midi/tree/bidirectional).

**Comment by starfishmod** [comment]
Wow that was quick! Thanks, just did some testing and it all seems to be working well so far :+1: 

I'll be doing some more thorough testing and development over the next few days and I'll let you know

Again thanks -this is awesome!
